package Interface;


public class JFInterfacePokedex extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePokedex
     */
    public JFInterfacePokedex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        CadastrarTreinador = new javax.swing.JMenuItem();
        BuscarTreinador = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        BuscaPorNome = new javax.swing.JMenuItem();
        BuscaPorTipo = new javax.swing.JMenuItem();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setText("Treinadores");

        CadastrarTreinador.setText("Cadastrar Treinador");
        CadastrarTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarTreinadorActionPerformed(evt);
            }
        });
        jMenu2.add(CadastrarTreinador);

        BuscarTreinador.setText("Buscar Treinador");
        BuscarTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTreinadorActionPerformed(evt);
            }
        });
        jMenu2.add(BuscarTreinador);

        jMenu1.setText("Pokemons");
        jMenu1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jMenu1AncestorMoved(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        BuscaPorNome.setText("Buscar por Nome");
        BuscaPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaPorNomeActionPerformed(evt);
            }
        });
        jMenu1.add(BuscaPorNome);

        BuscaPorTipo.setText("Buscar por Tipo");
        BuscaPorTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaPorTipoActionPerformed(evt);
            }
        });
        jMenu1.add(BuscaPorTipo);

        jMenu2.add(jMenu1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(621, 437));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscaPorTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaPorTipoActionPerformed
        // TODO add your handling code here:
        
        JFBuscarPorTipo obj= new JFBuscarPorTipo();
        jdpprincipal.add(obj);
        obj.setVisible(true);
        
    }//GEN-LAST:event_BuscaPorTipoActionPerformed

    private void CadastrarTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarTreinadorActionPerformed
        // TODO add your handling code here:
        
        JFCadastrarTreinador obj = new JFCadastrarTreinador();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_CadastrarTreinadorActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenu1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1AncestorMoved

    private void BuscaPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaPorNomeActionPerformed
        // TODO add your handling code here:
        
        JFBuscarporNome obj = new JFBuscarporNome();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_BuscaPorNomeActionPerformed

    private void BuscarTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTreinadorActionPerformed
        // TODO add your handling code here:
        
        JFBuscarTreinador obj = new JFBuscarTreinador();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_BuscarTreinadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInterfacePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInterfacePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInterfacePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInterfacePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInterfacePokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuscaPorNome;
    private javax.swing.JMenuItem BuscaPorTipo;
    private javax.swing.JMenuItem BuscarTreinador;
    private javax.swing.JMenuItem CadastrarTreinador;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
